
import type { PatientVisit } from "@/components/ui/custom_ui/PatientHistoryTable";

export const MOCK_PATIENT_VISITS: PatientVisit[] = [
    {
        id: "v001",
        patientName: "Amara Keita",
        age: 34,
        gender: "Female",
        visitDate: "2026-03-12",
        visitTime: "09:00",
        visitType: "consultation",
        diagnosis: "Acute Sinusitis",
        prescription: "Amoxicillin 500 mg, Nasal saline rinse",
        status: "completed",
        notes: "Follow-up in 2 weeks if symptoms persist.",
    },
    {
        id: "v002",
        patientName: "Rohan Mehta",
        age: 47,
        gender: "Male",
        visitDate: "2026-03-12",
        visitTime: "10:30",
        visitType: "follow-up",
        diagnosis: "Hypertension – BP 148/92",
        prescription: "Amlodipine 5 mg daily",
        status: "completed",
        notes: "Advised low-sodium diet and daily walks.",
    },
    {
        id: "v003",
        patientName: "Sofia Castellano",
        age: 28,
        gender: "Female",
        visitDate: "2026-03-12",
        visitTime: "11:15",
        visitType: "lab",
        diagnosis: "Anaemia – CBC pending",
        prescription: "Iron supplements pending results",
        status: "pending",
    },
    {
        id: "v004",
        patientName: "James Okafor",
        age: 61,
        gender: "Male",
        visitDate: "2026-03-12",
        visitTime: "13:00",
        visitType: "consultation",
        diagnosis: "Type 2 Diabetes – HbA1c 8.1%",
        prescription: "Metformin 500 mg twice daily, dietary plan",
        status: "in-progress",
        notes: "Referred to nutritionist.",
    },
    {
        id: "v005",
        patientName: "Mei Lin",
        age: 22,
        gender: "Female",
        visitDate: "2026-03-11",
        visitTime: "14:00",
        visitType: "consultation",
        diagnosis: "Seasonal Allergic Rhinitis",
        prescription: "Cetirizine 10 mg, Fluticasone nasal spray",
        status: "completed",
    },
    {
        id: "v006",
        patientName: "Carlos Rivera",
        age: 55,
        gender: "Male",
        visitDate: "2026-03-11",
        visitTime: "09:30",
        visitType: "procedure",
        diagnosis: "Lipoma removal – left forearm",
        prescription: "Betadine dressing, Ibuprofen 400 mg PRN",
        status: "completed",
        notes: "Minor excision under local anaesthesia.",
    },
    {
        id: "v007",
        patientName: "Priya Nair",
        age: 39,
        gender: "Female",
        visitDate: "2026-03-11",
        visitTime: "11:00",
        visitType: "follow-up",
        diagnosis: "Hypothyroidism",
        prescription: "Levothyroxine 50 mcg morning",
        status: "completed",
    },
    {
        id: "v008",
        patientName: "Tariq Al-Rashid",
        age: 44,
        gender: "Male",
        visitDate: "2026-03-10",
        visitTime: "08:45",
        visitType: "consultation",
        diagnosis: "Migraine with Aura",
        prescription: "Sumatriptan 50 mg PRN, Topiramate 25 mg preventive",
        status: "completed",
        notes: "Advised to keep a migraine diary.",
    },
    {
        id: "v009",
        patientName: "Yuki Tanaka",
        age: 17,
        gender: "Female",
        visitDate: "2026-03-10",
        visitTime: "10:00",
        visitType: "lab",
        diagnosis: "Suspected Mononucleosis",
        prescription: "Rest, paracetamol; awaiting Monospot result",
        status: "pending",
    },
    {
        id: "v010",
        patientName: "Emmanuel Diop",
        age: 31,
        gender: "Male",
        visitDate: "2026-03-10",
        visitTime: "15:30",
        visitType: "consultation",
        diagnosis: "Gastritis",
        prescription: "Omeprazole 20 mg, avoid NSAIDs",
        status: "completed",
    },
    {
        id: "v011",
        patientName: "Lena Schulz",
        age: 52,
        gender: "Female",
        visitDate: "2026-03-09",
        visitTime: "09:15",
        visitType: "follow-up",
        diagnosis: "Rheumatoid Arthritis – stable",
        prescription: "Methotrexate 15 mg weekly, folic acid",
        status: "completed",
    },
    {
        id: "v012",
        patientName: "David Osei",
        age: 68,
        gender: "Male",
        visitDate: "2026-03-09",
        visitTime: "11:45",
        visitType: "consultation",
        diagnosis: "COPD – moderate exacerbation",
        prescription: "Salbutamol inhaler, Prednisolone 30 mg 5-day course",
        status: "completed",
        notes: "Chest X-ray ordered.",
    },
    {
        id: "v013",
        patientName: "Aisha Malik",
        age: 26,
        gender: "Female",
        visitDate: "2026-03-09",
        visitTime: "14:30",
        visitType: "consultation",
        diagnosis: "Urinary Tract Infection",
        prescription: "Trimethoprim 200 mg for 7 days, increased fluids",
        status: "cancelled",
        notes: "Patient did not attend; rescheduled.",
    },
    {
        id: "v014",
        patientName: "Park Ji-hoon",
        age: 38,
        gender: "Male",
        visitDate: "2026-03-08",
        visitTime: "10:15",
        visitType: "procedure",
        diagnosis: "Ingrowing toenail – right hallux",
        prescription: "Wedge resection, Augmentin 625 mg",
        status: "completed",
    },
    {
        id: "v015",
        patientName: "Fatima Al-Zahrani",
        age: 49,
        gender: "Female",
        visitDate: "2026-03-08",
        visitTime: "13:30",
        visitType: "lab",
        diagnosis: "Dyslipidaemia – lipid panel review",
        prescription: "Atorvastatin 40 mg if LDL > 4.0",
        status: "completed",
        notes: "Results reviewed; statin initiated.",
    },
    {
        id: "v016",
        patientName: "Omar Hassan",
        age: 72,
        gender: "Male",
        visitDate: "2026-03-07",
        visitTime: "09:00",
        visitType: "follow-up",
        diagnosis: "Post-MI cardiac review",
        prescription: "Aspirin 75 mg, Bisoprolol 5 mg, Atorvastatin 80 mg",
        status: "completed",
        notes: "Echo requested; BP 130/80.",
    },
];

export const STATS = {
    totalToday: MOCK_PATIENT_VISITS.filter(v => v.visitDate === "2026-03-12").length,
    completedToday: MOCK_PATIENT_VISITS.filter(v => v.visitDate === "2026-03-12" && v.status === "completed").length,
    pendingToday: MOCK_PATIENT_VISITS.filter(v => v.visitDate === "2026-03-12" && v.status === "pending").length,
    inProgressToday: MOCK_PATIENT_VISITS.filter(v => v.visitDate === "2026-03-12" && v.status === "in-progress").length,
    allTime: MOCK_PATIENT_VISITS.length,
};
